export interface SurahMeta {
  number: number;
  name: string;
  nameArabic: string;
  englishTranslation: string;
  ayahCount: number;
  revelationType: "Meccan" | "Medinan";
}

export const surahs: SurahMeta[] = [
  { number: 1, name: "Al-Fatihah", nameArabic: "الفاتحة", englishTranslation: "The Opening", ayahCount: 7, revelationType: "Meccan" },
  { number: 2, name: "Al-Baqarah", nameArabic: "البقرة", englishTranslation: "The Cow", ayahCount: 286, revelationType: "Medinan" },
  { number: 3, name: "Aal-E-Imran", nameArabic: "آل عمران", englishTranslation: "The Family of Imran", ayahCount: 200, revelationType: "Medinan" },
  { number: 4, name: "An-Nisa", nameArabic: "النساء", englishTranslation: "The Women", ayahCount: 176, revelationType: "Medinan" },
  { number: 5, name: "Al-Ma'idah", nameArabic: "المائدة", englishTranslation: "The Table Spread", ayahCount: 120, revelationType: "Medinan" },
  { number: 6, name: "Al-An'am", nameArabic: "الأنعام", englishTranslation: "The Cattle", ayahCount: 165, revelationType: "Meccan" },
  { number: 7, name: "Al-A'raf", nameArabic: "الأعراف", englishTranslation: "The Heights", ayahCount: 206, revelationType: "Meccan" },
  { number: 8, name: "Al-Anfal", nameArabic: "الأنفال", englishTranslation: "The Spoils of War", ayahCount: 75, revelationType: "Medinan" },
  { number: 9, name: "At-Tawbah", nameArabic: "التوبة", englishTranslation: "The Repentance", ayahCount: 129, revelationType: "Medinan" },
  { number: 10, name: "Yunus", nameArabic: "يونس", englishTranslation: "Jonah", ayahCount: 109, revelationType: "Meccan" },
  { number: 11, name: "Hud", nameArabic: "هود", englishTranslation: "Hud", ayahCount: 123, revelationType: "Meccan" },
  { number: 12, name: "Yusuf", nameArabic: "يوسف", englishTranslation: "Joseph", ayahCount: 111, revelationType: "Meccan" },
  { number: 13, name: "Ar-Ra'd", nameArabic: "الرعد", englishTranslation: "The Thunder", ayahCount: 43, revelationType: "Medinan" },
  { number: 14, name: "Ibrahim", nameArabic: "ابراهيم", englishTranslation: "Abraham", ayahCount: 52, revelationType: "Meccan" },
  { number: 15, name: "Al-Hijr", nameArabic: "الحجر", englishTranslation: "The Rocky Tract", ayahCount: 99, revelationType: "Meccan" },
  { number: 16, name: "An-Nahl", nameArabic: "النحل", englishTranslation: "The Bee", ayahCount: 128, revelationType: "Meccan" },
  { number: 17, name: "Al-Isra", nameArabic: "الإسراء", englishTranslation: "The Night Journey", ayahCount: 111, revelationType: "Meccan" },
  { number: 18, name: "Al-Kahf", nameArabic: "الكهف", englishTranslation: "The Cave", ayahCount: 110, revelationType: "Meccan" },
  { number: 19, name: "Maryam", nameArabic: "مريم", englishTranslation: "Mary", ayahCount: 98, revelationType: "Meccan" },
  { number: 20, name: "Ta-Ha", nameArabic: "طه", englishTranslation: "Ta-Ha", ayahCount: 135, revelationType: "Meccan" },
  { number: 21, name: "Al-Anbiya", nameArabic: "الأنبياء", englishTranslation: "The Prophets", ayahCount: 112, revelationType: "Meccan" },
  { number: 22, name: "Al-Hajj", nameArabic: "الحج", englishTranslation: "The Pilgrimage", ayahCount: 78, revelationType: "Medinan" },
  { number: 23, name: "Al-Mu'minun", nameArabic: "المؤمنون", englishTranslation: "The Believers", ayahCount: 118, revelationType: "Meccan" },
  { number: 24, name: "An-Nur", nameArabic: "النور", englishTranslation: "The Light", ayahCount: 64, revelationType: "Medinan" },
  { number: 25, name: "Al-Furqan", nameArabic: "الفرقان", englishTranslation: "The Criterion", ayahCount: 77, revelationType: "Meccan" },
  { number: 26, name: "Ash-Shu'ara", nameArabic: "الشعراء", englishTranslation: "The Poets", ayahCount: 227, revelationType: "Meccan" },
  { number: 27, name: "An-Naml", nameArabic: "النمل", englishTranslation: "The Ant", ayahCount: 93, revelationType: "Meccan" },
  { number: 28, name: "Al-Qasas", nameArabic: "القصص", englishTranslation: "The Stories", ayahCount: 88, revelationType: "Meccan" },
  { number: 29, name: "Al-Ankabut", nameArabic: "العنكبوت", englishTranslation: "The Spider", ayahCount: 69, revelationType: "Meccan" },
  { number: 30, name: "Ar-Rum", nameArabic: "الروم", englishTranslation: "The Romans", ayahCount: 60, revelationType: "Meccan" },
  { number: 31, name: "Luqman", nameArabic: "لقمان", englishTranslation: "Luqman", ayahCount: 34, revelationType: "Meccan" },
  { number: 32, name: "As-Sajdah", nameArabic: "السجدة", englishTranslation: "The Prostration", ayahCount: 30, revelationType: "Meccan" },
  { number: 33, name: "Al-Ahzab", nameArabic: "الأحزاب", englishTranslation: "The Combined Forces", ayahCount: 73, revelationType: "Medinan" },
  { number: 34, name: "Saba", nameArabic: "سبإ", englishTranslation: "Sheba", ayahCount: 54, revelationType: "Meccan" },
  { number: 35, name: "Fatir", nameArabic: "فاطر", englishTranslation: "Originator", ayahCount: 45, revelationType: "Meccan" },
  { number: 36, name: "Ya-Sin", nameArabic: "يس", englishTranslation: "Ya Sin", ayahCount: 83, revelationType: "Meccan" },
  { number: 37, name: "As-Saffat", nameArabic: "الصافات", englishTranslation: "Those who set the Ranks", ayahCount: 182, revelationType: "Meccan" },
  { number: 38, name: "Sad", nameArabic: "ص", englishTranslation: "The Letter Sad", ayahCount: 88, revelationType: "Meccan" },
  { number: 39, name: "Az-Zumar", nameArabic: "الزمر", englishTranslation: "The Troops", ayahCount: 75, revelationType: "Meccan" },
  { number: 40, name: "Ghafir", nameArabic: "غافر", englishTranslation: "The Forgiver", ayahCount: 85, revelationType: "Meccan" },
  { number: 41, name: "Fussilat", nameArabic: "فصلت", englishTranslation: "Explained in Detail", ayahCount: 54, revelationType: "Meccan" },
  { number: 42, name: "Ash-Shuraa", nameArabic: "الشورى", englishTranslation: "The Consultation", ayahCount: 53, revelationType: "Meccan" },
  { number: 43, name: "Az-Zukhruf", nameArabic: "الزخرف", englishTranslation: "The Gold Adornments", ayahCount: 89, revelationType: "Meccan" },
  { number: 44, name: "Ad-Dukhan", nameArabic: "الدخان", englishTranslation: "The Smoke", ayahCount: 59, revelationType: "Meccan" },
  { number: 45, name: "Al-Jathiyah", nameArabic: "الجاثية", englishTranslation: "The Crouching", ayahCount: 37, revelationType: "Meccan" },
  { number: 46, name: "Al-Ahqaf", nameArabic: "الأحقاف", englishTranslation: "The Wind-Curved Sandhills", ayahCount: 35, revelationType: "Meccan" },
  { number: 47, name: "Muhammad", nameArabic: "محمد", englishTranslation: "Muhammad", ayahCount: 38, revelationType: "Medinan" },
  { number: 48, name: "Al-Fath", nameArabic: "الفتح", englishTranslation: "The Victory", ayahCount: 29, revelationType: "Medinan" },
  { number: 49, name: "Al-Hujurat", nameArabic: "الحجرات", englishTranslation: "The Rooms", ayahCount: 18, revelationType: "Medinan" },
  { number: 50, name: "Qaf", nameArabic: "ق", englishTranslation: "The Letter Qaf", ayahCount: 45, revelationType: "Meccan" },
  { number: 51, name: "Adh-Dhariyat", nameArabic: "الذاريات", englishTranslation: "The Winnowing Winds", ayahCount: 60, revelationType: "Meccan" },
  { number: 52, name: "At-Tur", nameArabic: "الطور", englishTranslation: "The Mount", ayahCount: 49, revelationType: "Meccan" },
  { number: 53, name: "An-Najm", nameArabic: "النجم", englishTranslation: "The Star", ayahCount: 62, revelationType: "Meccan" },
  { number: 54, name: "Al-Qamar", nameArabic: "القمر", englishTranslation: "The Moon", ayahCount: 55, revelationType: "Meccan" },
  { number: 55, name: "Ar-Rahman", nameArabic: "الرحمن", englishTranslation: "The Beneficent", ayahCount: 78, revelationType: "Medinan" },
  { number: 56, name: "Al-Waqi'ah", nameArabic: "الواقعة", englishTranslation: "The Inevitable", ayahCount: 96, revelationType: "Meccan" },
  { number: 57, name: "Al-Hadid", nameArabic: "الحديد", englishTranslation: "The Iron", ayahCount: 29, revelationType: "Medinan" },
  { number: 58, name: "Al-Mujadila", nameArabic: "المجادلة", englishTranslation: "The Pleading Woman", ayahCount: 22, revelationType: "Medinan" },
  { number: 59, name: "Al-Hashr", nameArabic: "الحشر", englishTranslation: "The Exile", ayahCount: 24, revelationType: "Medinan" },
  { number: 60, name: "Al-Mumtahanah", nameArabic: "الممتحنة", englishTranslation: "She that is to be examined", ayahCount: 13, revelationType: "Medinan" },
  { number: 61, name: "As-Saf", nameArabic: "الصف", englishTranslation: "The Ranks", ayahCount: 14, revelationType: "Medinan" },
  { number: 62, name: "Al-Jumu'ah", nameArabic: "الجمعة", englishTranslation: "Friday", ayahCount: 11, revelationType: "Medinan" },
  { number: 63, name: "Al-Munafiqun", nameArabic: "المنافقون", englishTranslation: "The Hypocrites", ayahCount: 11, revelationType: "Medinan" },
  { number: 64, name: "At-Taghabun", nameArabic: "التغابن", englishTranslation: "The Mutual Disillusion", ayahCount: 18, revelationType: "Medinan" },
  { number: 65, name: "At-Talaq", nameArabic: "الطلاق", englishTranslation: "The Divorce", ayahCount: 12, revelationType: "Medinan" },
  { number: 66, name: "At-Tahrim", nameArabic: "التحريم", englishTranslation: "The Prohibition", ayahCount: 12, revelationType: "Medinan" },
  { number: 67, name: "Al-Mulk", nameArabic: "الملك", englishTranslation: "The Sovereignty", ayahCount: 30, revelationType: "Meccan" },
  { number: 68, name: "Al-Qalam", nameArabic: "القلم", englishTranslation: "The Pen", ayahCount: 52, revelationType: "Meccan" },
  { number: 69, name: "Al-Haqqah", nameArabic: "الحاقة", englishTranslation: "The Reality", ayahCount: 52, revelationType: "Meccan" },
  { number: 70, name: "Al-Ma'arij", nameArabic: "المعارج", englishTranslation: "The Ascending Stairways", ayahCount: 44, revelationType: "Meccan" },
  { number: 71, name: "Nuh", nameArabic: "نوح", englishTranslation: "Noah", ayahCount: 28, revelationType: "Meccan" },
  { number: 72, name: "Al-Jinn", nameArabic: "الجن", englishTranslation: "The Jinn", ayahCount: 28, revelationType: "Meccan" },
  { number: 73, name: "Al-Muzzammil", nameArabic: "المزمل", englishTranslation: "The Enshrouded One", ayahCount: 20, revelationType: "Meccan" },
  { number: 74, name: "Al-Muddaththir", nameArabic: "المدثر", englishTranslation: "The Cloaked One", ayahCount: 56, revelationType: "Meccan" },
  { number: 75, name: "Al-Qiyamah", nameArabic: "القيامة", englishTranslation: "The Resurrection", ayahCount: 40, revelationType: "Meccan" },
  { number: 76, name: "Al-Insan", nameArabic: "الانسان", englishTranslation: "The Man", ayahCount: 31, revelationType: "Medinan" },
  { number: 77, name: "Al-Mursalat", nameArabic: "المرسلات", englishTranslation: "The Emissaries", ayahCount: 50, revelationType: "Meccan" },
  { number: 78, name: "An-Naba", nameArabic: "النبإ", englishTranslation: "The Tidings", ayahCount: 40, revelationType: "Meccan" },
  { number: 79, name: "An-Nazi'at", nameArabic: "النازعات", englishTranslation: "Those who drag forth", ayahCount: 46, revelationType: "Meccan" },
  { number: 80, name: "Abasa", nameArabic: "عبس", englishTranslation: "He Frowned", ayahCount: 42, revelationType: "Meccan" },
  { number: 81, name: "At-Takwir", nameArabic: "التكوير", englishTranslation: "The Overthrowing", ayahCount: 29, revelationType: "Meccan" },
  { number: 82, name: "Al-Infitar", nameArabic: "الإنفطار", englishTranslation: "The Cleaving", ayahCount: 19, revelationType: "Meccan" },
  { number: 83, name: "Al-Mutaffifin", nameArabic: "المطففين", englishTranslation: "Defrauding", ayahCount: 36, revelationType: "Meccan" },
  { number: 84, name: "Al-Inshiqaq", nameArabic: "الإنشقاق", englishTranslation: "The Sundering", ayahCount: 25, revelationType: "Meccan" },
  { number: 85, name: "Al-Buruj", nameArabic: "البروج", englishTranslation: "The Mansions of the Stars", ayahCount: 22, revelationType: "Meccan" },
  { number: 86, name: "At-Tariq", nameArabic: "الطارق", englishTranslation: "The Nightcommer", ayahCount: 17, revelationType: "Meccan" },
  { number: 87, name: "Al-A'la", nameArabic: "الأعلى", englishTranslation: "The Most High", ayahCount: 19, revelationType: "Meccan" },
  { number: 88, name: "Al-Ghashiyah", nameArabic: "الغاشية", englishTranslation: "The Overwhelming", ayahCount: 26, revelationType: "Meccan" },
  { number: 89, name: "Al-Fajr", nameArabic: "الفجر", englishTranslation: "The Dawn", ayahCount: 30, revelationType: "Meccan" },
  { number: 90, name: "Al-Balad", nameArabic: "البلد", englishTranslation: "The City", ayahCount: 20, revelationType: "Meccan" },
  { number: 91, name: "Ash-Shams", nameArabic: "الشمس", englishTranslation: "The Sun", ayahCount: 15, revelationType: "Meccan" },
  { number: 92, name: "Al-Layl", nameArabic: "الليل", englishTranslation: "The Night", ayahCount: 21, revelationType: "Meccan" },
  { number: 93, name: "Ad-Duhaa", nameArabic: "الضحى", englishTranslation: "The Morning Hours", ayahCount: 11, revelationType: "Meccan" },
  { number: 94, name: "Ash-Sharh", nameArabic: "الشرح", englishTranslation: "The Relief", ayahCount: 8, revelationType: "Meccan" },
  { number: 95, name: "At-Tin", nameArabic: "التين", englishTranslation: "The Fig", ayahCount: 8, revelationType: "Meccan" },
  { number: 96, name: "Al-Alaq", nameArabic: "العلق", englishTranslation: "The Clot", ayahCount: 19, revelationType: "Meccan" },
  { number: 97, name: "Al-Qadr", nameArabic: "القدر", englishTranslation: "The Power", ayahCount: 5, revelationType: "Meccan" },
  { number: 98, name: "Al-Bayyinah", nameArabic: "البينة", englishTranslation: "The Clear Proof", ayahCount: 8, revelationType: "Medinan" },
  { number: 99, name: "Az-Zalzalah", nameArabic: "الزلزلة", englishTranslation: "The Earthquake", ayahCount: 8, revelationType: "Medinan" },
  { number: 100, name: "Al-Adiyat", nameArabic: "العاديات", englishTranslation: "The Courser", ayahCount: 11, revelationType: "Meccan" },
  { number: 101, name: "Al-Qari'ah", nameArabic: "القارعة", englishTranslation: "The Calamity", ayahCount: 11, revelationType: "Meccan" },
  { number: 102, name: "At-Takathur", nameArabic: "التكاثر", englishTranslation: "Rivalry in world increase", ayahCount: 8, revelationType: "Meccan" },
  { number: 103, name: "Al-Asr", nameArabic: "العصر", englishTranslation: "The Declining Day", ayahCount: 3, revelationType: "Meccan" },
  { number: 104, name: "Al-Humazah", nameArabic: "الهمزة", englishTranslation: "The Traducer", ayahCount: 9, revelationType: "Meccan" },
  { number: 105, name: "Al-Fil", nameArabic: "الفيل", englishTranslation: "The Elephant", ayahCount: 5, revelationType: "Meccan" },
  { number: 106, name: "Quraysh", nameArabic: "قريش", englishTranslation: "Quraysh", ayahCount: 4, revelationType: "Meccan" },
  { number: 107, name: "Al-Ma'un", nameArabic: "الماعون", englishTranslation: "The Small Kindnesses", ayahCount: 7, revelationType: "Meccan" },
  { number: 108, name: "Al-Kawthar", nameArabic: "الكوثر", englishTranslation: "The Abundance", ayahCount: 3, revelationType: "Meccan" },
  { number: 109, name: "Al-Kafirun", nameArabic: "الكافرون", englishTranslation: "The Disbelievers", ayahCount: 6, revelationType: "Meccan" },
  { number: 110, name: "An-Nasr", nameArabic: "النصر", englishTranslation: "The Divine Support", ayahCount: 3, revelationType: "Medinan" },
  { number: 111, name: "Al-Masad", nameArabic: "المسد", englishTranslation: "The Palm Fiber", ayahCount: 5, revelationType: "Meccan" },
  { number: 112, name: "Al-Ikhlas", nameArabic: "الإخلاص", englishTranslation: "The Sincerity", ayahCount: 4, revelationType: "Meccan" },
  { number: 113, name: "Al-Falaq", nameArabic: "الفلق", englishTranslation: "The Daybreak", ayahCount: 5, revelationType: "Meccan" },
  { number: 114, name: "An-Nas", nameArabic: "الناس", englishTranslation: "Mankind", ayahCount: 6, revelationType: "Meccan" },
];

export const TOTAL_PAGES = 604;

export function getSurah(number: number): SurahMeta | undefined {
  return surahs.find((s) => s.number === number);
}
